### ISSUE TITLE
Desired attribution?

### ISSUE THREAD

**Issue by forthguy** [cyber-simon/idp-auth-linotp#4]
I wonder if you could provide the desired copyright attribution for the project's files.

I started off planning to make a few tweaks and submit some pull requests, as I tweaked things to fit in the 3.3 MFA flow.  Then, I went a little astray and started refactoring, renaming classes, restructuring config initialization, etc.  I may also wedge in some additional actions that we need to go along with this.  At that point, I think it may end up that it makes more sense just to put it out as a new project rather than submitting some omnibus, wildly different bits as a pull request (or series of pull requests.)  If so, I'd like to know the correct attribution (that doesn't currently exist in the files) to meet 4b and 4c of the Apache 2.0 license.

**Comment by cyber-simon** [comment]
Please have a look if those changes are sufficient.

**Comment by forthguy** [comment]
Yup. That's great.  Thanks.
