### ISSUE TITLE
Rename properties

### ISSUE THREAD

**Issue by icb-** [cyber-simon/idp-auth-linotp#5]
Shibboleth reserves property names starting with `idp.` for their own use. See http://shibboleth.net/pipermail/users/2017-June/036507.html and following messages in that thread.

These should probably be renamed:
> idp.authn.linotpHost
> idp.authn.linotpServiceuser
> idp.authn.linotpServicepassword
> idp.authn.linotpCheckcert
> idp.authn.linotpCreateEmailToken

I would suggest either using `edu.kit.scc.linotp` or just `linotp` as the prefix, and drop the `linotp` from the last component of the property name.

**Comment by cyber-simon** [comment]
You're right. Thank's for the hint and sorry it took me so long.
I used your suggestion linotp.* as prefix.
